// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL9mSmBshVhXbtvqztllugt3PCQ2oS5rY',
    appId: '1:156121637252:web:259f41329c4ac7c3f4fdd1',
    messagingSenderId: '156121637252',
    projectId: 'hackathon-28353',
    authDomain: 'hackathon-28353.firebaseapp.com',
    storageBucket: 'hackathon-28353.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEu5M0G8OFNQB089iOi3-5iKZWz460sVw',
    appId: '1:156121637252:android:0cab8aedb330d07bf4fdd1',
    messagingSenderId: '156121637252',
    projectId: 'hackathon-28353',
    storageBucket: 'hackathon-28353.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIMeOR95i_hRUynTAX16fmuP1oZcPyr3U',
    appId: '1:156121637252:ios:d163ae1f0fb54ebbf4fdd1',
    messagingSenderId: '156121637252',
    projectId: 'hackathon-28353',
    storageBucket: 'hackathon-28353.appspot.com',
    iosClientId: '156121637252-3lo38tugsi45s3tm2ee7nio1tdbs4q9k.apps.googleusercontent.com',
    iosBundleId: 'com.example.freelancy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIMeOR95i_hRUynTAX16fmuP1oZcPyr3U',
    appId: '1:156121637252:ios:d163ae1f0fb54ebbf4fdd1',
    messagingSenderId: '156121637252',
    projectId: 'hackathon-28353',
    storageBucket: 'hackathon-28353.appspot.com',
    iosClientId: '156121637252-3lo38tugsi45s3tm2ee7nio1tdbs4q9k.apps.googleusercontent.com',
    iosBundleId: 'com.example.freelancy',
  );
}
